---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - tomcat8
    - tomcat8-install

- include: "config-{{ ansible_os_family }}.yml"
  static: no
  tags:
    - tomcat8
    - tomcat8-config
